title: InsightGinie Archive
description: Article mirror of insightginie.com
tagline: News of Tomorrow
locale: en_US

url: "https://github.insightginie.com"
baseurl: ""

markdown: kramdown

sass:
  sass_dir: assets/css
  style: compressed

permalink: /:slug/

collections:
  posts:
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-archives

pagination:
  enabled: true
  per_page: 100
  permalink: '/page/:num/'
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Jekyll Archives Configuration (FIXES 404 CATEGORY PAGES)
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: category
    subcategory: subcategory
  permalinks:
    category: '/:name/'
    subcategory: '/:parent/:name/'
  hierarchical_categories: true
