title: InsightGinie Archive
description: Article mirror of insightginie.com
tagline: News of Tomorrow
locale: en_US

url: "https://github.insightginie.com"
baseurl: ""
future: true

markdown: kramdown

sass:
  sass_dir: assets/css
  style: compressed

permalink: /:slug/

collections:
  posts:
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 100
paginate_path: "/page/:num/"


